runtime: python39
env: standard
instance_class: F1
handlers:
  - url: /static/(.*)
    static_files: static/\1
    require_matching_file: false
    upload: static/.*
  - url: /.*
    script: auto
  - url: .*
    script: auto
automatic_scaling:
  min_instances: 0
  max_instances: 3
  min_idle_instances: 0
  max_idle_instances: 2
  min_pending_latency: 1500ms
  max_pending_latency: automatic
network: {}